### ISSUE TITLE
Have you got a plugin ver?

### ISSUE THREAD

**Issue by BagroSlave** [Nicolol1234/More-Music-Disk#2]
I wana use on my server, but i like to use plugins, mb you know about fork of your datapack.

**Comment by Nicolol1234** [comment]
it should work on any fork, spigot, paper, purpur...

**Comment by BagroSlave** [comment]
how can i use this like plugin?

**Comment by Nicolol1234** [comment]
oh, you can't, but if you want to use it, just use this datapacks with other plugins

**Comment by BagroSlave** [comment]
ok
